name: GitHub Actions Demo MK

on: 
  push:
    branches: [main]
    paths-ignore: [.gihub/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
jobs:
  Builds:
    runs-on: latest-ubuntu
    steps:
      - run: | 
          echo "Job was triggered by event ${{github.event_name}}" 
          echo "Name of the branch is ${{github.ref}}"
      - uses: actions/checkout@v3.3.0
      - name: List files in repository
      - run: | 
          echo "The repository ${{ github.repository }} contains the following files:"
          tree  
